<?php

namespace AppBundle\Repository;

/**
 * ChatTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatTabRepository extends \Doctrine\ORM\EntityRepository
{
}
