<?php

namespace AppBundle\Repository;

/**
 * MessageTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTabRepository extends \Doctrine\ORM\EntityRepository
{
}
