<?php

namespace AppBundle\Repository;

/**
 * MessagesTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesTabRepository extends \Doctrine\ORM\EntityRepository
{
}
