<?php

namespace AppBundle\Repository;

/**
 * UserTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTabRepository extends \Doctrine\ORM\EntityRepository
{
}
